remove some cruft from run-dsi

diff --git a/run-genny b/run-genny
--- a/run-genny
+++ b/run-genny
@@ -13,11 +13,6 @@ pushd "$(dirname "$0")" >/dev/null
 popd >/dev/null
 
 
-if [[ $# -lt 1 ]]; then
-    echo -e "Usage: \\n\\t$0 setup\\n\\t$0 command" >/dev/stderr
-    exit 5
-fi
-
 if [ -d "/opt/mongodbtoolchain/v3/bin" ]; then
     export PATH="/opt/mongodbtoolchain/v3/bin:$PATH"
 fi
@@ -31,7 +26,7 @@ _print_diagnostics() {
     if [ -n "$_HAVE_PRINTED_DIAGNOSTICS" ]; then
         return
     fi
-    echo >&2 "If you're stuck, please reach out to the #performance MongoDB slack channel and paste this output."
+    echo >&2 "If you're stuck, please reach out to the #workload-generation MongoDB slack channel and paste this output."
     echo >&2 ""
     echo >&2 "  git rev-parse HEAD: $(git rev-parse HEAD)"
     echo >&2 "  uname -a:           $(uname -a)"
@@ -57,9 +52,9 @@ if ! python3 -c 'import sys; sys.exit(1 if sys.version_info < (3, 7) else 0)' >/
     exit 1
 fi
 
-if [ -n "${VIRTUAL_ENV:-}" ] && [ "${VIRTUAL_ENV}" != "${GENNY_REPO_ROOT}/dsi_venv" ]; then
+if [ -n "${VIRTUAL_ENV:-}" ] && [ "${VIRTUAL_ENV}" != "${GENNY_REPO_ROOT}/genny_venv" ]; then
     echo >&2 "You are already inside a virtual environment $VIRTUAL_ENV."
-    echo >&2 "This can be problematic. Will try to proceed, but setup may fail."
+    echo >&2 "This can be problematic. Will try to proceed, but the operation may fail."
     echo >&2 "If it does, please deactivate your existing virtualenv first:"
     echo >&2 ""
     echo >&2 "    deactivate"
@@ -73,7 +68,7 @@ if which pyenv >/dev/null 2>&1; then
         echo >&2 "You have system python setup through pyenv."
         echo >&2 "pyenv version: $(pyenv version)"
         echo >&2 ""
-        echo >&2 "This can be problematic. Will try to proceed, but setup may fail."
+        echo >&2 "This can be problematic. Will try to proceed, but the operation may fail."
         echo >&2 "If it does, please change your python version by doing something like this:"
         echo >&2 ""
         echo >&2 "    echo '3.7.0' > ~/.python-version"
@@ -120,7 +115,7 @@ if [[ ! -d "${GENNY_REPO_ROOT}/${_genny_venv}" || ! -e "${GENNY_REPO_ROOT}/${_ge
     # shellcheck source=/dev/null
     source "${GENNY_REPO_ROOT}/${_genny_venv}/bin/activate"
 
-    # Install DSI requirements
+    # Install Genny requirements
     _pip install -r "${GENNY_REPO_ROOT}/src/lamplib/requirements.txt"
 
     _pip freeze > "pip-requirements.txt" 2>/dev/null
@@ -140,4 +135,4 @@ export VIRTUAL_ENV_DISABLE_PROMPT=1  # prevent undefined $PS1 variable
 # shellcheck source=/dev/null
 source "${GENNY_REPO_ROOT}/${_genny_venv}/bin/activate"
 
-PYTHONPATH="${GENNY_REPO_ROOT}/src:${PYTHONPATH:-}" python3 "${GENNY_REPO_ROOT}/src/lamplib/cli.py" "${COMMAND[@]}"
+python3 "${GENNY_REPO_ROOT}/src/lamplib/cli.py" "${COMMAND[@]}"
